### ISSUE TITLE
Epic: Helm chart support for container deployment

### ISSUE THREAD

**Issue by stevefan1999-personal** [NodeBB/NodeBB#12178]
### Description

As a long term follow up for https://github.com/NodeBB/NodeBB/pull/12031
Here's what I would do

- [ ] Managed DB: MongoDB
- [ ] Managed DB: Postgres
- [ ] Managed DB: Redis
- [ ] External config support
- [ ] Persistent volume cache for both node_modules and public build
- [ ] Publish to Github Pages
