### ISSUE TITLE
Replace custom attributes with data attributes

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/NodeBB#5435]
Follow-up of https://github.com/NodeBB/NodeBB/issues/5432:
There are several div tags with "widget-area" attributes found in [several themes](https://github.com/NodeBB/nodebb-theme-persona/search?utf8=%E2%9C%93&q=widget-area)...
As pointed out by @psychobunny, changing this into data-widget-area immediately would break a lot of themes.
The same applies also to "has-widget-class", "has-widget-target" and the widely used "component" attribute
This issue adresses the plan to change that in the next major version.

**Comment by pitaj** [comment]
There is a possibility that the widget system will be completely refactored soon for lots of good reasons. So that may result in indirectly fixing this issue.

### Todo list

#### Components
- [ ] Introduce `data-component` in core themes:
  + [ ] Persona
  + [ ] Lavender
  + [ ] Vanilla
- [ ] Adapt core component code to recognize the `data-component` attribute, with temporary backwards compatibility
- [ ] Eventually remove recognition of the old attribute in core code

#### Widgets
- [ ] Introduce `data-widget-area`, `data-has-widget-class`, and `data-has-widget-target` in core themes:
  + [ ] Persona
  + [ ] Lavender
  + [ ] Vanilla
- [ ] Adapt core code to recognize the `data-` prepended attributes, with temporary backwards compatibility
- [ ] Eventually remove recognition of the old attributes in core code

**Comment by mySebbe** [comment]
This is now superseded by #14551, which tracks the exact remaining `component` to `data-component` migration. Current Core still permits `component` in the sanitizer specifically until that migration is complete, so a second implementation path here would duplicate the compatibility work across Core, themes, and plugins. I suggest closing this older issue and keeping migration staging and compatibility notes on #14551.
